version: '3.8'

services:
  python-app:
    build: .
    container_name: python-app
    ports:
      - "8000:8000"
    volumes:
      - /home/hrvision/category.ggkit:/app
    working_dir: /app
    command: python main.py
    restart: unless-stopped
